name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Runs every day at 00:00 UTC
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          username: saputsav10
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu

